import sys

path = r'C:\Development\ez-flash-ii-usb-flasher\src\ezwriter-cli\src\main.rs'
with open(path, 'r', encoding='utf-8') as f:
    text = f.read()

# Replace the entire drain+warmup+non-pipelined loop section
old = (
    '    // Drain + warmup: consume stale EP2 IN data then consume firmware phantom packet.\n'
    '    // Print byte counts to diagnose alignment.\n'
    '    {\n'
    '        let mut drain = [0u8; 64];\n'
    '        let mut d_iter = 0u32;\n'
    '        loop {\n'
    '            match handle.read_bulk(0x82, &mut drain, Duration::from_millis(100)) {\n'
    '                Ok(n) if n > 0 => {\n'
    '                    eprintln!("  [DIAG] drain iter {d_iter}: read {n} bytes (first4={:02X?})", &drain[..4]);\n'
    '                    d_iter += 1;\n'
    '                    if d_iter >= 8 { break; }\n'
    '                }\n'
    '                Ok(n) => { eprintln!("  [DIAG] drain iter {d_iter}: read {n} bytes (timeout/zero) -> stop"); break; }\n'
    '                Err(e) => { eprintln!("  [DIAG] drain iter {d_iter}: err={e} -> stop"); break; }\n'
    '            }\n'
    '        }\n'
    '    }\n'
    '    {\n'
    '        let warmup = [0x01u8, 0x00, 0x00, 0x00];\n'
    '        let _ = handle.write_bulk(0x04, &warmup, TIMEOUT);\n'
    '        std::thread::sleep(Duration::from_millis(150));\n'
    '        // Each cmd generates 2 EP2 IN responses (phantom + data). Consume both.\n'
    '        for i in 0..2 {\n'
    '            let mut phantom = [0u8; 64];\n'
    '            match handle.read_bulk(0x82, &mut phantom, Duration::from_millis(500)) {\n'
    '                Ok(n) => eprintln!("  [DIAG] warmup[{i}]: read {n} bytes (first4={:02X?})", &phantom[..4]),\n'
    '                Err(e) => eprintln!("  [DIAG] warmup[{i}]: err={e}"),\n'
    '            }\n'
    '        }\n'
    '    }'
)

new = (
    '    // The EZ-Flash II firmware maintains a 8-chunk (512-byte) auto-stream ring in\n'
    '    // EP2 IN that advances with every USB IN transfer, independent of EP4 OUT cmds.\n'
    '    // Step 1: drain all 8 auto-stream slots to clear the ring.\n'
    '    for _ in 0..8 {\n'
    '        let mut drain = [0u8; 64];\n'
    '        let _ = handle.read_bulk(0x82, &mut drain, Duration::from_millis(200));\n'
    '    }\n'
    '    // Step 2: prime — send cmd addr=start_addr which loads ROM[start_addr] into the\n'
    '    // prefetch buffer; the firmware responds with a phantom packet first.\n'
    '    // Read the phantom and discard it; ROM[start_addr] is now prefetched.\n'
    '    {\n'
    '        let prime_word = start_addr / 2;\n'
    '        let prime_a16 = (prime_word & 0xFFFF) as u16;\n'
    '        let prime_bank = (prime_word >> 16) as u8;\n'
    '        let prime_cmd = [0x01u8, (prime_a16 & 0xFF) as u8, ((prime_a16 >> 8) & 0xFF) as u8, prime_bank];\n'
    '        let _ = handle.write_bulk(0x04, &prime_cmd, TIMEOUT);\n'
    '        std::thread::sleep(Duration::from_millis(150));\n'
    '        let mut phantom = [0u8; 64];\n'
    '        let _ = handle.read_bulk(0x82, &mut phantom, Duration::from_secs(1));\n'
    '    }'
)

if old not in text:
    print('ERROR: drain+warmup block not found', file=sys.stderr)
    sys.exit(1)
text = text.replace(old, new, 1)

# Fix the non-pipelined loop: send cmd ONE CHUNK AHEAD so reads get current chunk
old2 = (
    '        // Reliable non-pipelined EP4 bulk protocol.\n'
    '        // Matches the behavior of `cart-read` and the GUI\'s small-read path.\n'
    '        let mut last_pct = 0u32;\n'
    '        for chunk in 0..chunk_count {\n'
    '            let byte_addr = start_addr + chunk * 64;\n'
    '            let word_addr = byte_addr / 2;\n'
    '            let addr_16 = (word_addr & 0xFFFF) as u16;\n'
    '            let bank = (word_addr >> 16) as u8;\n'
    '\n'
    '            let cmd = [\n'
    '                0x01u8,\n'
    '                (addr_16 & 0xFF) as u8,\n'
    '                ((addr_16 >> 8) & 0xFF) as u8,\n'
    '                bank,\n'
    '            ];\n'
    '\n'
    '            handle.write_bulk(cmd_ep, &cmd, TIMEOUT)\n'
    '                .with_context(|| format!("EP4 ROM write at byte_addr=0x{byte_addr:06X}"))?;\n'
    '\n'
    '            // 100 ms: enough for firmware to process cmd and fill EP2 IN\n'
    '            std::thread::sleep(Duration::from_millis(100));\n'
    '\n'
    '            let mut buf = [0u8; 64];\n'
    '            match handle.read_bulk(data_ep, &mut buf, Duration::from_secs(3)) {\n'
    '                Ok(len) => {\n'
    '                    eprintln!("  [DIAG] chunk {chunk} addr=0x{byte_addr:06X}: read {len} bytes (first4={:02X?})", &buf[..4]);\n'
    '                    file.write_all(&buf[..len])?;\n'
    '                }\n'
    '                Err(e) => {\n'
    '                    println!("\\n  ERROR at chunk {chunk}: read_bulk: {e}");\n'
    '                    break;\n'
    '                }\n'
    '            }\n'
    '\n'
    '            let pct = (chunk * 100) / chunk_count;\n'
    '            if pct != last_pct {\n'
    '                last_pct = pct;\n'
    '                let addr_mb = byte_addr as f64 / (1024.0 * 1024.0);\n'
    '                print!("\\r  Progress: {pct}% ({addr_mb:.1} MB)");\n'
    '                use std::io::Write;\n'
    '                std::io::stdout().flush()?;\n'
    '            }\n'
    '        }'
)

new2 = (
    '        // Non-pipelined: the firmware prefetches; send cmd addr+64 ahead so the\n'
    '        // current chunk is already buffered and available to read immediately.\n'
    '        // The prime already loaded ROM[start_addr]; each cmd loads the NEXT chunk.\n'
    '        let mut last_pct = 0u32;\n'
    '        for chunk in 0..chunk_count {\n'
    '            let byte_addr = start_addr + chunk * 64;         // what we\'re reading now\n'
    '            let next_addr = start_addr + (chunk + 1) * 64;  // what to prefetch next\n'
    '            let next_word = next_addr / 2;\n'
    '            let next_a16 = (next_word & 0xFFFF) as u16;\n'
    '            let next_bank = (next_word >> 16) as u8;\n'
    '\n'
    '            let cmd = [\n'
    '                0x01u8,\n'
    '                (next_a16 & 0xFF) as u8,\n'
    '                ((next_a16 >> 8) & 0xFF) as u8,\n'
    '                next_bank,\n'
    '            ];\n'
    '\n'
    '            handle.write_bulk(cmd_ep, &cmd, TIMEOUT)\n'
    '                .with_context(|| format!("EP4 ROM write at byte_addr=0x{byte_addr:06X}"))?;\n'
    '\n'
    '            // 5 ms: data is already prefetched; just time for state transition\n'
    '            std::thread::sleep(Duration::from_millis(5));\n'
    '\n'
    '            let mut buf = [0u8; 64];\n'
    '            match handle.read_bulk(data_ep, &mut buf, Duration::from_secs(3)) {\n'
    '                Ok(len) => {\n'
    '                    file.write_all(&buf[..len])?;\n'
    '                }\n'
    '                Err(e) => {\n'
    '                    println!("\\n  ERROR at chunk {chunk}: read_bulk: {e}");\n'
    '                    break;\n'
    '                }\n'
    '            }\n'
    '\n'
    '            let pct = (chunk * 100) / chunk_count;\n'
    '            if pct != last_pct {\n'
    '                last_pct = pct;\n'
    '                let addr_mb = byte_addr as f64 / (1024.0 * 1024.0);\n'
    '                print!("\\r  Progress: {pct}% ({addr_mb:.1} MB)");\n'
    '                use std::io::Write;\n'
    '                std::io::stdout().flush()?;\n'
    '            }\n'
    '        }'
)

if old2 not in text:
    print('ERROR: non-pipelined loop not found', file=sys.stderr)
    sys.exit(1)
text = text.replace(old2, new2, 1)

with open(path, 'w', encoding='utf-8') as f:
    f.write(text)
print('OK')
